# main text of home
nombre: 
bio: 

# twitter summary info
description:

picture: Captura de pantalla 2025-09-04 132458.png

url: https://melanieguadalupe.me/
# your url:

# if you don't have any of social below, comment the line
instagram: 
twitter:
github: 
email:

gems:
  - jekyll-seo-tag

exclude:
