# main text of Blog perosnal
name: MELANIE
bio: holaaaa

description:Blog persomnal 

picture: (Captura de pantalla 2025-09-04 132458.png)

url: http://koppl.in/violet
# your url: http://USERNAME. github.10

# mis redes sociales 
facebook: mi facebook
twitter: mi twitter
github: mi github
instagram: mi instagram
spotify: mi spotify

gems:
- jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
